version: "3.9"
services:
  database_inventory:
    image: postgres
    container_name: database_inventory
    user: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: inventory
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_inventory
    depends_on:
      - database_inventory
    
volumes:
  pgdata:
    driver: local